### ISSUE TITLE
HTML page is rendered twice 

### ISSUE THREAD

**Issue by WhoKnocks** [htmlpreview/htmlpreview.github.com#38]
The html page that I want to preview is rendered twice in htmlpreview.github.io 

Issue in htmlpreview, page is rendered a second time underneath the first one: 
https://htmlpreview.github.io/?https://raw.githubusercontent.com/WhoKnocks/Elm-TodoList/master/main.html

Page hosted on github: https://github.com/WhoKnocks/Elm-TodoList/blob/master/main.html

Opening the file in Edge,Firefox or Chrome only shows the page once as expected.

The page is originally written in Elm.

**Comment by niutech** [comment]
This is because `HTMLPreview.replaceAssets()` invokes `Elm.fullscreen(Elm.Main)` once more. This is usually needed when you want to fire a script after loading a JS file using `<script src=""></script>`, which is not the case with you. I will need to change how `replaceAssets` works. In the meantime you can move Elm to a separate JS file and it should work as intented.
